"""empty message

Revision ID: 0fd9a8998050
Revises: d5e359250b95
Create Date: 2025-09-11 02:50:02.787432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd9a8998050'
down_revision = 'd5e359250b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.alter_column('planet_Id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_Id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###